# Generated by Django 4.2.5 on 2023-11-23 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='has_resume',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='hours',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='profilePicture',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
